Fix error in MRI 2.3 in model plugin
MRI 2.4+ allows `nil.dup`, but in MRI 2.3 that still raises

  TypeError: can't dup NilClass

So we avoid calling `nil.dup`